/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package firebase.config;

import com.google.firebase.remoteconfig.FirebaseRemoteConfig;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import com.google.android.gms.tasks.OnSuccessListener;

import java.util.HashMap;

@Kroll.module(name="TitaniumFirebaseConfig", id="firebase.config")
public class TitaniumFirebaseConfigModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TitaniumFirebaseConfigModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TitaniumFirebaseConfigModule()
	{
		super();
	}

	// Methods

	@Kroll.method
	public void fetch(KrollDict params)
	{
		final KrollFunction callback = (KrollFunction) params.get("callback");
		int expirationDuration = params.getInt("expirationDuration");

		FirebaseRemoteConfig.getInstance().fetch(expirationDuration).addOnSuccessListener(new OnSuccessListener<Void>() {
			@Override
			public void onSuccess(Void aVoid) {
				callback.callAsync(getKrollObject(), new KrollDict());
			}
		});
	}

	@Kroll.method
	public void setDefaults(Object params) throws Exception {
		if (params instanceof Integer) {
			FirebaseRemoteConfig.getInstance().setDefaults(TiConvert.toInt(params));
		} else if (params instanceof HashMap) {
			FirebaseRemoteConfig.getInstance().setDefaults((HashMap) params);
		} else {
			throw new Exception("Invalid defaults provided. Please either pass a dictionary or string");
		}
	}

	@Kroll.method
	public boolean activateFetched()
	{
		return FirebaseRemoteConfig.getInstance().activateFetched();
	}

	@Kroll.method
	public KrollDict configValueForKey(String key)
	{
		String stringValue = FirebaseRemoteConfig.getInstance().getString(key);
		boolean boolValue = FirebaseRemoteConfig.getInstance().getBoolean(key);
		double numberValue = FirebaseRemoteConfig.getInstance().getDouble(key);

		KrollDict result = new KrollDict();
		result.put("bool", boolValue);
		result.put("number", numberValue);

		if (stringValue != null) {
			result.put("string", stringValue);
		}

		return result;
	}
}

